# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommsMessages",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("thread_id", models.TextField()),
                ("sender_user_id", models.TextField(blank=True, null=True)),
                ("sender_name", models.TextField()),
                ("sender_type", models.TextField()),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "comms_messages",
            },
        ),
        migrations.CreateModel(
            name="CommsThreads",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("type", models.TextField()),
                ("title", models.TextField(blank=True, null=True)),
                ("pinned", models.IntegerField()),
                ("status", models.TextField(blank=True, null=True)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("target_investors", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "comms_threads",
            },
        ),
        migrations.CreateModel(
            name="SharedThreads",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("conversation_id", models.TextField()),
                ("agent_id", models.TextField(blank=True, null=True)),
                ("shared_by", models.TextField()),
                ("shared_with", models.TextField()),
                ("message_id", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "shared_threads",
            },
        ),
        migrations.CreateModel(
            name="Threads",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("agent_id", models.TextField(blank=True, null=True)),
                ("user_email", models.TextField()),
                ("participants", models.JSONField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("visibility", models.TextField(blank=True, null=True)),
                ("thread_type", models.TextField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("message_count", models.IntegerField(blank=True, null=True)),
                ("agents_json", models.JSONField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("cross_hub", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "threads",
            },
        ),
        migrations.CreateModel(
            name="UserPresence",
            fields=[
                ("user_email", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("last_active_at", models.DateTimeField()),
                ("current_agent_id", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_presence",
            },
        ),
    ]
