# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnrichmentLog",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("contact_id", models.TextField(blank=True, null=True)),
                ("company_id", models.TextField(blank=True, null=True)),
                ("source", models.TextField()),
                ("request_type", models.TextField(blank=True, null=True)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("fields_filled", models.TextField(blank=True, null=True)),
                ("fields_skipped", models.TextField(blank=True, null=True)),
                ("cost_credits", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "enrichment_log",
            },
        ),
        migrations.CreateModel(
            name="ImportBatches",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("source", models.TextField()),
                ("imported_by", models.TextField()),
                ("status", models.TextField()),
                ("total_records", models.IntegerField(blank=True, null=True)),
                ("valid_records", models.IntegerField(blank=True, null=True)),
                ("imported_records", models.IntegerField(blank=True, null=True)),
                ("merged_records", models.IntegerField(blank=True, null=True)),
                ("dropped_records", models.IntegerField(blank=True, null=True)),
                ("enriched_records", models.IntegerField(blank=True, null=True)),
                ("error_details", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "import_batches",
            },
        ),
        migrations.CreateModel(
            name="ImportLinks",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("token", models.TextField(unique=True)),
                ("created_by", models.TextField()),
                ("label", models.TextField(blank=True, null=True)),
                ("scopes", models.JSONField(blank=True, null=True)),
                ("max_uses", models.IntegerField(blank=True, null=True)),
                ("use_count", models.IntegerField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "import_links",
            },
        ),
        migrations.CreateModel(
            name="IngestionPreviews",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("agent_id", models.TextField()),
                ("user_email", models.TextField()),
                ("filename", models.TextField(blank=True, null=True)),
                ("file_type", models.TextField(blank=True, null=True)),
                ("status", models.TextField()),
                ("proposed_changes", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("applied_by", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "ingestion_previews",
            },
        ),
    ]
