# Generated by Django 5.1.15 on 2026-04-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("owner", models.TextField()),
                ("status", models.TextField()),
                ("health", models.TextField()),
                ("monthly_value", models.FloatField(blank=True, null=True)),
                ("margin_pct", models.FloatField(blank=True, null=True)),
                ("renewal_date", models.TextField(blank=True, null=True)),
                ("last_touch", models.TextField(blank=True, null=True)),
                ("next_action", models.TextField(blank=True, null=True)),
                ("next_action_date", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("stripe_customer_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "clients",
            },
        ),
        migrations.CreateModel(
            name="EntityStatus",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("entity_name", models.TextField()),
                ("entity_type", models.TextField()),
                ("owner", models.TextField()),
                ("cash_position", models.FloatField(blank=True, null=True)),
                ("monthly_burn", models.FloatField(blank=True, null=True)),
                ("runway_months", models.FloatField(blank=True, null=True)),
                ("status", models.TextField()),
                ("health", models.TextField()),
                ("current_milestone", models.TextField(blank=True, null=True)),
                ("next_action", models.TextField(blank=True, null=True)),
                ("next_action_owner", models.TextField(blank=True, null=True)),
                ("blockers", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "entity_status",
            },
        ),
        migrations.CreateModel(
            name="HubEvents",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("event_type", models.TextField()),
                ("actor_type", models.TextField()),
                ("actor_id", models.TextField()),
                ("entity_type", models.TextField(blank=True, null=True)),
                ("entity_id", models.TextField(blank=True, null=True)),
                ("detail", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "hub_events",
            },
        ),
        migrations.CreateModel(
            name="HubFeedback",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("type", models.TextField()),
                ("agent_id", models.TextField(blank=True, null=True)),
                ("run_id", models.TextField(blank=True, null=True)),
                ("user_email", models.TextField()),
                ("content", models.TextField(blank=True, null=True)),
                ("agent_response", models.TextField(blank=True, null=True)),
                ("data_context", models.TextField(blank=True, null=True)),
                ("status", models.TextField()),
                ("resolved_by", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "hub_feedback",
            },
        ),
        migrations.CreateModel(
            name="HubRegistry",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("hostname", models.TextField()),
                ("db_binding", models.TextField()),
                ("db_id", models.TextField(blank=True, null=True)),
                ("owner_email", models.TextField(blank=True, null=True)),
                ("plan", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "hub_registry",
            },
        ),
        migrations.CreateModel(
            name="HubRelays",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("from_email", models.TextField()),
                ("to_email", models.TextField()),
                ("subject", models.TextField()),
                ("context", models.TextField(blank=True, null=True)),
                ("source_agent_id", models.TextField(blank=True, null=True)),
                ("source_conversation_id", models.TextField(blank=True, null=True)),
                ("source_run_id", models.TextField(blank=True, null=True)),
                ("response_conversation_id", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("priority", models.TextField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("response_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("relay_type", models.TextField(blank=True, null=True)),
                ("thread_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hub_relays",
            },
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("target_type", models.TextField()),
                ("target_id", models.TextField()),
                ("author", models.TextField()),
                ("content", models.TextField()),
                ("is_private", models.IntegerField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "notes",
            },
        ),
        migrations.CreateModel(
            name="PortalActivityLog",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("investor_profile_id", models.TextField()),
                ("action", models.TextField()),
                ("detail", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "portal_activity_log",
            },
        ),
        migrations.CreateModel(
            name="PortfolioCompanies",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("type", models.TextField()),
                ("sector", models.TextField(blank=True, null=True)),
                ("stage", models.TextField(blank=True, null=True)),
                ("founded", models.TextField(blank=True, null=True)),
                ("sprint_investment", models.IntegerField(blank=True, null=True)),
                ("sprint_ownership_pct", models.FloatField(blank=True, null=True)),
                ("sprint_equity_pct", models.FloatField(blank=True, null=True)),
                ("cost_basis", models.IntegerField(blank=True, null=True)),
                ("current_valuation", models.IntegerField(blank=True, null=True)),
                ("sprint_position_value", models.IntegerField(blank=True, null=True)),
                ("mrr", models.IntegerField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("milestone", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("carta_fund_id", models.TextField(blank=True, null=True)),
                ("last_valuation_date", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "portfolio_companies",
            },
        ),
        migrations.CreateModel(
            name="TeamSignals",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("person_email", models.TextField()),
                ("period", models.TextField()),
                ("signal", models.TextField()),
                ("signal_color", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("slack_activity_trend", models.FloatField(blank=True, null=True)),
                ("last_project_update_days", models.IntegerField(blank=True, null=True)),
                ("last_client_touch_days", models.IntegerField(blank=True, null=True)),
                ("tasks_completed_this_week", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "team_signals",
            },
        ),
        migrations.CreateModel(
            name="ClientContacts",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("email", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("role", models.TextField(blank=True, null=True)),
                ("is_primary", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="hub_app.clients"
                    ),
                ),
            ],
            options={
                "db_table": "client_contacts",
            },
        ),
        migrations.CreateModel(
            name="Entities",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("legal_name", models.TextField()),
                ("type", models.TextField()),
                ("jurisdiction", models.TextField(blank=True, null=True)),
                ("status", models.TextField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "parent_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hub_app.entities",
                    ),
                ),
            ],
            options={
                "db_table": "entities",
            },
        ),
        migrations.CreateModel(
            name="Deals",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("owner", models.TextField()),
                ("type", models.TextField(blank=True, null=True)),
                ("stage", models.TextField()),
                ("amount", models.FloatField(blank=True, null=True)),
                ("probability", models.FloatField(blank=True, null=True)),
                ("close_date", models.TextField(blank=True, null=True)),
                ("counterparty", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="hub_app.entities"
                    ),
                ),
            ],
            options={
                "db_table": "deals",
            },
        ),
        migrations.AddField(
            model_name="clients",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="hub_app.entities"
            ),
        ),
        migrations.CreateModel(
            name="HubRelationships",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("parent_tenant_id", models.TextField()),
                ("child_tenant_id", models.TextField()),
                ("relationship_type", models.TextField(blank=True, null=True)),
                ("permissions_json", models.JSONField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "hub_relationships",
                "unique_together": {("parent_tenant_id", "child_tenant_id")},
            },
        ),
        migrations.CreateModel(
            name="Initiatives",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("division", models.TextField(blank=True, null=True)),
                ("owner", models.TextField()),
                ("status", models.TextField()),
                ("health", models.TextField()),
                ("current_milestone", models.TextField(blank=True, null=True)),
                ("next_action", models.TextField(blank=True, null=True)),
                ("next_action_date", models.TextField(blank=True, null=True)),
                ("target_date", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("labs_visible", models.IntegerField(blank=True, null=True)),
                ("labs_stage", models.TextField(blank=True, null=True)),
                ("labs_section", models.TextField(blank=True, null=True)),
                ("labs_tagline", models.TextField(blank=True, null=True)),
                ("labs_description", models.TextField(blank=True, null=True)),
                ("labs_icon", models.TextField(blank=True, null=True)),
                ("labs_color", models.TextField(blank=True, null=True)),
                ("labs_url", models.TextField(blank=True, null=True)),
                ("labs_waitlist_url", models.TextField(blank=True, null=True)),
                ("labs_demo_type", models.TextField(blank=True, null=True)),
                ("labs_demo_source", models.TextField(blank=True, null=True)),
                ("labs_sort_order", models.IntegerField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="hub_app.entities"
                    ),
                ),
            ],
            options={
                "db_table": "initiatives",
            },
        ),
        migrations.CreateModel(
            name="Milestones",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("status", models.TextField()),
                ("due_date", models.TextField(blank=True, null=True)),
                ("completed_date", models.TextField(blank=True, null=True)),
                ("owner", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="hub_app.initiatives"
                    ),
                ),
            ],
            options={
                "db_table": "milestones",
            },
        ),
        migrations.CreateModel(
            name="TeamSignalHistory",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("person_email", models.TextField()),
                ("date", models.TextField()),
                ("signal", models.TextField()),
                ("metrics_json", models.JSONField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "team_signal_history",
                "unique_together": {("person_email", "date")},
            },
        ),
    ]
