# Generated by Django 5.1.15 on 2026-04-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElleJourneys",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("agent_id", models.TextField()),
                ("trigger_type", models.TextField()),
                ("trigger_filter", models.TextField(blank=True, null=True)),
                ("steps_json", models.JSONField()),
                ("active", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "elle_journeys",
            },
        ),
        migrations.CreateModel(
            name="ElleAgentScores",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("agent_id", models.TextField()),
                ("total_journeys", models.IntegerField(blank=True, null=True)),
                ("passed_journeys", models.IntegerField(blank=True, null=True)),
                ("failed_journeys", models.IntegerField(blank=True, null=True)),
                ("consecutive_passes", models.IntegerField(blank=True, null=True)),
                ("consecutive_fails", models.IntegerField(blank=True, null=True)),
                ("correction_rate_50", models.FloatField(blank=True, null=True)),
                ("correction_rate_200", models.FloatField(blank=True, null=True)),
                ("correction_rate_1000", models.FloatField(blank=True, null=True)),
                ("last_run_id", models.TextField(blank=True, null=True)),
                ("last_run_status", models.TextField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("recommended_level", models.IntegerField(blank=True, null=True)),
                ("current_level", models.IntegerField(blank=True, null=True)),
                ("security_violations", models.IntegerField(blank=True, null=True)),
                ("last_demotion_at", models.DateTimeField(blank=True, null=True)),
                ("last_promotion_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "elle_agent_scores",
                "unique_together": {("agent_id", "tenant_id")},
            },
        ),
        migrations.CreateModel(
            name="ElleRuns",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("status", models.TextField()),
                ("total_steps", models.IntegerField(blank=True, null=True)),
                ("passed_steps", models.IntegerField(blank=True, null=True)),
                ("failed_steps", models.IntegerField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("results_json", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="qa.ellejourneys"
                    ),
                ),
            ],
            options={
                "db_table": "elle_runs",
            },
        ),
        migrations.CreateModel(
            name="ElleAssertions",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("step_index", models.IntegerField()),
                ("step_name", models.TextField(blank=True, null=True)),
                ("assertion_type", models.TextField()),
                ("expected", models.TextField(blank=True, null=True)),
                ("actual", models.TextField(blank=True, null=True)),
                ("passed", models.IntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="qa.elleruns"
                    ),
                ),
            ],
            options={
                "db_table": "elle_assertions",
            },
        ),
    ]
