# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PricingAddons",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("price_cents", models.IntegerField()),
                ("billing_type", models.TextField()),
                ("billing_interval", models.TextField(blank=True, null=True)),
                ("tier_requirement", models.TextField(blank=True, null=True)),
                ("stripe_price_id", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("active", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "pricing_addons",
            },
        ),
    ]
