# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentApprovals",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("content_item_id", models.TextField()),
                ("approver_user_id", models.TextField()),
                ("approver_name", models.TextField()),
                ("action", models.TextField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "content_approvals",
            },
        ),
        migrations.CreateModel(
            name="ContentItems",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("ir_calendar_item_id", models.TextField(blank=True, null=True)),
                ("type", models.TextField()),
                ("title", models.TextField()),
                ("body", models.TextField(blank=True, null=True)),
                ("body_html", models.TextField(blank=True, null=True)),
                ("status", models.TextField()),
                ("author_user_id", models.TextField(blank=True, null=True)),
                ("author_name", models.TextField(blank=True, null=True)),
                ("required_approvals", models.IntegerField()),
                ("current_approvals", models.IntegerField()),
                ("scheduled_for", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("target_audience", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "content_items",
            },
        ),
        migrations.CreateModel(
            name="ContentLibrary",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("content_type", models.TextField()),
                ("body", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("target_audience", models.TextField(blank=True, null=True)),
                ("channel", models.TextField(blank=True, null=True)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "content_library",
            },
        ),
        migrations.CreateModel(
            name="DeckTemplates",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("deck_type", models.TextField()),
                ("slide_structure", models.JSONField()),
                ("data_sources", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "deck_templates",
            },
        ),
        migrations.CreateModel(
            name="IrCalendarItems",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("category", models.TextField()),
                ("type", models.TextField()),
                ("title", models.TextField()),
                ("period", models.TextField(blank=True, null=True)),
                ("due_date", models.TextField(blank=True, null=True)),
                ("review_by", models.TextField(blank=True, null=True)),
                ("status", models.TextField()),
                ("owner_user_id", models.TextField(blank=True, null=True)),
                ("owner_name", models.TextField(blank=True, null=True)),
                ("ai_suggested", models.IntegerField()),
                ("trigger_description", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("scheduled_for", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("content_item_id", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "ir_calendar_items",
            },
        ),
        migrations.CreateModel(
            name="IrCommunications",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("type", models.TextField()),
                ("title", models.TextField()),
                ("content", models.TextField(blank=True, null=True)),
                ("audience", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "ir_communications",
            },
        ),
        migrations.CreateModel(
            name="NarrativeContexts",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("entity", models.TextField()),
                ("status", models.TextField(blank=True, null=True)),
                ("positioning", models.TextField(blank=True, null=True)),
                ("key_facts", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "narrative_contexts",
            },
        ),
        migrations.CreateModel(
            name="NarrativeFaqs",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("entity", models.TextField()),
                ("audience", models.TextField()),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("source", models.TextField(blank=True, null=True)),
                ("verified", models.IntegerField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("pushed_to_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "narrative_faqs",
            },
        ),
        migrations.CreateModel(
            name="NarrativePushes",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("narrative_version_id", models.TextField()),
                ("target_agent", models.TextField()),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "narrative_pushes",
            },
        ),
        migrations.CreateModel(
            name="NarrativeSignals",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("source_agent", models.TextField()),
                ("signal_type", models.TextField()),
                ("entity", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("processed", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("data_json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "narrative_signals",
            },
        ),
        migrations.CreateModel(
            name="NarrativeThreads",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("user_email", models.TextField()),
                ("title", models.TextField()),
                ("entity", models.TextField(blank=True, null=True)),
                ("audience", models.TextField(blank=True, null=True)),
                ("messages_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "narrative_threads",
            },
        ),
        migrations.CreateModel(
            name="NarrativeVersions",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("variant", models.TextField()),
                ("audience", models.TextField()),
                ("title", models.TextField(blank=True, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("version", models.IntegerField(blank=True, null=True)),
                ("active", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("doc_type", models.TextField(blank=True, null=True)),
                ("owner", models.TextField(blank=True, null=True)),
                ("stale_reason", models.TextField(blank=True, null=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "narrative_versions",
            },
        ),
    ]
