# Generated by Django 5.1.15 on 2026-04-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hub_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalMatters",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("matter_type", models.TextField()),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.TextField()),
                ("priority", models.TextField(blank=True, null=True)),
                ("owner", models.TextField(blank=True, null=True)),
                ("counsel", models.TextField(blank=True, null=True)),
                ("deadline", models.TextField(blank=True, null=True)),
                ("decided_date", models.TextField(blank=True, null=True)),
                ("decided_by", models.TextField(blank=True, null=True)),
                ("decision_summary", models.TextField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("related_entity", models.TextField(blank=True, null=True)),
                ("related_matter_id", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "legal_matters",
            },
        ),
        migrations.CreateModel(
            name="Approvals",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("type", models.TextField()),
                ("source_agent", models.TextField(blank=True, null=True)),
                ("requested_by", models.TextField()),
                ("assigned_to", models.TextField()),
                ("risk_level", models.TextField()),
                ("summary", models.TextField()),
                ("detail", models.TextField(blank=True, null=True)),
                ("status", models.TextField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by", models.TextField(blank=True, null=True)),
                ("decision_comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="hub_app.entities"
                    ),
                ),
            ],
            options={
                "db_table": "approvals",
            },
        ),
        migrations.CreateModel(
            name="Decisions",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("owners", models.TextField()),
                ("decision_text", models.TextField()),
                ("options_considered", models.TextField(blank=True, null=True)),
                ("rationale", models.TextField(blank=True, null=True)),
                ("impact", models.TextField(blank=True, null=True)),
                ("follow_ups", models.JSONField(blank=True, null=True)),
                ("sources", models.TextField(blank=True, null=True)),
                ("status", models.TextField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("tenant_id", models.TextField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="hub_app.entities"
                    ),
                ),
            ],
            options={
                "db_table": "decisions",
            },
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("category", models.TextField()),
                ("owner", models.TextField()),
                ("status", models.TextField()),
                ("doc_url", models.TextField(blank=True, null=True)),
                ("next_action", models.TextField(blank=True, null=True)),
                ("next_action_date", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="hub_app.entities"
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="Governance",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("type", models.TextField()),
                ("owner", models.TextField()),
                ("status", models.TextField()),
                ("due_date", models.TextField(blank=True, null=True)),
                ("completed_date", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="hub_app.entities"
                    ),
                ),
            ],
            options={
                "db_table": "governance",
            },
        ),
    ]
