# Generated by Django 5.1.15 on 2026-04-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hub_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentWorkQueue",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("agent_id", models.TextField()),
                ("action_type", models.TextField()),
                ("payload", models.JSONField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("result", models.TextField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cost_usd", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "agent_work_queue",
            },
        ),
        migrations.CreateModel(
            name="AutomationCoverage",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("process_name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("current_method", models.TextField(blank=True, null=True)),
                ("hub_replacement", models.TextField(blank=True, null=True)),
                ("hub_ready", models.IntegerField(blank=True, null=True)),
                ("monthly_cost_manual", models.FloatField(blank=True, null=True)),
                ("monthly_cost_hub", models.FloatField(blank=True, null=True)),
                ("savings_monthly", models.FloatField(blank=True, null=True)),
                ("priority", models.TextField(blank=True, null=True)),
                ("assigned_to", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "automation_coverage",
            },
        ),
        migrations.CreateModel(
            name="CardSnooze",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("card_id", models.TextField(blank=True, null=True)),
                ("user_email", models.TextField(blank=True, null=True)),
                ("snooze_until", models.DateTimeField(blank=True, null=True)),
                ("dismissed", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "card_snooze",
            },
        ),
        migrations.CreateModel(
            name="PartnerCommitments",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("partner_email", models.TextField()),
                ("commitment", models.TextField()),
                ("source", models.TextField(blank=True, null=True)),
                ("due_date", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("nudge_count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "partner_commitments",
            },
        ),
        migrations.CreateModel(
            name="ProjectDependencies",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("source_initiative_id", models.TextField()),
                ("target_initiative_id", models.TextField()),
                ("dependency_type", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "project_dependencies",
            },
        ),
        migrations.CreateModel(
            name="RateLimits",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("count", models.IntegerField()),
                ("window_start", models.DateTimeField()),
            ],
            options={
                "db_table": "rate_limits",
            },
        ),
        migrations.CreateModel(
            name="WorkflowRuns",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("workflow_id", models.TextField()),
                ("trigger_event", models.TextField(blank=True, null=True)),
                ("actions_executed_json", models.JSONField(blank=True, null=True)),
                ("status", models.TextField()),
                ("error", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("workflow_type", models.TextField(blank=True, null=True)),
                ("triggered_by", models.TextField(blank=True, null=True)),
                ("steps", models.TextField(blank=True, null=True)),
                ("current_step", models.IntegerField(blank=True, null=True)),
                ("context", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "workflow_runs",
            },
        ),
        migrations.CreateModel(
            name="Workflows",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("entity_id", models.TextField(blank=True, null=True)),
                ("trigger_type", models.TextField()),
                ("trigger_config_json", models.JSONField(blank=True, null=True)),
                ("actions_json", models.JSONField(blank=True, null=True)),
                ("status", models.TextField()),
                ("created_by", models.TextField(blank=True, null=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "workflows",
            },
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("owner", models.TextField()),
                ("priority", models.TextField()),
                ("status", models.TextField()),
                ("due_date", models.TextField(blank=True, null=True)),
                ("source", models.TextField()),
                ("source_agent", models.TextField(blank=True, null=True)),
                ("requires_approval", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("chain_id", models.TextField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="hub_app.entities"
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hub_app.initiatives",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
            },
        ),
    ]
