# Generated by Django 5.1.15 on 2026-04-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientInvoices",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("client_id", models.TextField()),
                ("number", models.TextField(blank=True, null=True)),
                ("amount", models.FloatField()),
                ("status", models.TextField()),
                ("date", models.TextField(blank=True, null=True)),
                ("due_date", models.TextField(blank=True, null=True)),
                ("paid_date", models.TextField(blank=True, null=True)),
                ("qb_invoice_id", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("stripe_invoice_id", models.TextField(blank=True, null=True)),
                ("stripe_customer_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "client_invoices",
            },
        ),
        migrations.CreateModel(
            name="ClientMessages",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("client_id", models.TextField()),
                ("sender_email", models.TextField()),
                ("sender_name", models.TextField()),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("is_internal", models.IntegerField()),
            ],
            options={
                "db_table": "client_messages",
            },
        ),
        migrations.CreateModel(
            name="ClientUsers",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("email", models.TextField(unique=True)),
                ("client_id", models.TextField()),
                ("name", models.TextField()),
                ("role", models.TextField(blank=True, null=True)),
                ("status", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "client_users",
            },
        ),
        migrations.CreateModel(
            name="HubSubscriptions",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField(unique=True)),
                ("plan", models.TextField()),
                ("stripe_customer_id", models.TextField(blank=True, null=True)),
                ("stripe_subscription_id", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("mrr_cents", models.IntegerField(blank=True, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("billing_email", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("billing_cycle", models.TextField(blank=True, null=True)),
                ("current_period_end", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "hub_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="SaasSubscriptions",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("tool_name", models.TextField()),
                ("vendor", models.TextField(blank=True, null=True)),
                ("monthly_cost", models.FloatField(blank=True, null=True)),
                ("annual_cost", models.FloatField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("hub_replacement_agent", models.TextField(blank=True, null=True)),
                ("replacement_status", models.TextField(blank=True, null=True)),
                ("replacement_notes", models.TextField(blank=True, null=True)),
                ("dependencies_json", models.JSONField(blank=True, null=True)),
                ("data_migrated", models.IntegerField(blank=True, null=True)),
                ("cancel_date", models.TextField(blank=True, null=True)),
                ("savings_to_date", models.FloatField(blank=True, null=True)),
                ("active", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "saas_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionChanges",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("change_type", models.TextField()),
                ("old_plan", models.TextField(blank=True, null=True)),
                ("new_plan", models.TextField(blank=True, null=True)),
                ("addon_id", models.TextField(blank=True, null=True)),
                ("stripe_event_id", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "subscription_changes",
            },
        ),
        migrations.CreateModel(
            name="TenantInvites",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("email", models.TextField()),
                ("role", models.TextField(blank=True, null=True)),
                ("invited_by", models.TextField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "tenant_invites",
                "unique_together": {("tenant_id", "email")},
            },
        ),
        migrations.CreateModel(
            name="SubscriptionAddons",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("status", models.TextField()),
                ("quantity", models.IntegerField()),
                ("stripe_subscription_item_id", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="pricing.pricingaddons"
                    ),
                ),
            ],
            options={
                "db_table": "subscription_addons",
                "unique_together": {("tenant_id", "addon")},
            },
        ),
    ]
