# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlendedClones",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("clone_weights", models.TextField(blank=True, null=True)),
                ("purpose", models.TextField(blank=True, null=True)),
                ("active", models.IntegerField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "blended_clones",
            },
        ),
        migrations.CreateModel(
            name="CloneDecisions",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("clone_id", models.TextField(blank=True, null=True)),
                ("scenario_id", models.TextField(blank=True, null=True)),
                ("clone_decision", models.TextField(blank=True, null=True)),
                ("human_decision", models.TextField(blank=True, null=True)),
                ("agreement", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "clone_decisions",
            },
        ),
        migrations.CreateModel(
            name="CloneProfiles",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("user_email", models.TextField()),
                ("clone_name", models.TextField(blank=True, null=True)),
                ("operating_manual", models.TextField(blank=True, null=True)),
                ("decision_frameworks", models.TextField(blank=True, null=True)),
                ("communication_style", models.TextField(blank=True, null=True)),
                ("priorities", models.TextField(blank=True, null=True)),
                ("quality_bar", models.TextField(blank=True, null=True)),
                ("blind_spots", models.TextField(blank=True, null=True)),
                ("strengths", models.TextField(blank=True, null=True)),
                ("common_phrases", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("training_progress", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "clone_profiles",
            },
        ),
        migrations.CreateModel(
            name="CloneScenarios",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("context", models.TextField(blank=True, null=True)),
                ("expected_decision", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "clone_scenarios",
            },
        ),
        migrations.CreateModel(
            name="CloneTrainingSignals",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("clone_id", models.TextField(blank=True, null=True)),
                ("signal_type", models.TextField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("context", models.TextField(blank=True, null=True)),
                ("decision_made", models.TextField(blank=True, null=True)),
                ("outcome", models.TextField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "clone_training_signals",
            },
        ),
        migrations.CreateModel(
            name="TrainingNeeds",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("person_email", models.TextField()),
                ("skill_name", models.TextField()),
                ("current_level", models.TextField(blank=True, null=True)),
                ("target_level", models.TextField(blank=True, null=True)),
                ("priority", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "training_needs",
            },
        ),
        migrations.CreateModel(
            name="UserPatterns",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("user_email", models.TextField()),
                ("pattern_type", models.TextField()),
                ("pattern", models.TextField()),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("is_active", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_patterns",
            },
        ),
    ]
