#!/usr/bin/env python3
"""Generate local-dev/caddy/Caddyfile from local-dev/routing-table.json.

Run by `make local-up` and `make reload-routing`. The Caddyfile is checked
in (derivable + small) so the container can mount it directly.

Schema (input):
    {
      "routes": [
        { "path": "/api/_smoke/*", "target": "django" },
        { "path": "/api/*", "target": "mock" }
      ]
    }

Rules:
- Routes are emitted most-specific first -> first match wins in Caddy.
- "django" target => reverse_proxy django:8000
- "mock"   target => reverse_proxy mock-legacy:8787
- SSE passthrough: flush_interval -1 disables response buffering.
- Local CORS is enabled so the Vite frontend on localhost:5173 can call Caddy.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import TypedDict

TARGETS = {
    "django": "django:8000",
    "mock": "mock-legacy:8787",
}

HERE = Path(__file__).resolve().parent
ROUTING_TABLE = HERE.parent / "routing-table.json"
CADDYFILE = HERE / "Caddyfile"


class Route(TypedDict):
    path: str
    target: str


def _route_specificity(route: Route) -> tuple[int, int]:
    path = route["path"]
    exact_bonus = 1 if not path.endswith("*") else 0
    return (len(path.rstrip("*")), exact_bonus)


def _validate_route(route: object, idx: int) -> Route:
    if not isinstance(route, dict):
        raise ValueError(f"route #{idx} must be an object")

    path = route.get("path")
    target = route.get("target")
    if not isinstance(path, str) or not path.startswith("/"):
        raise ValueError(f"route #{idx} path must be an absolute path")
    if "*" in path[:-1]:
        raise ValueError(f"route #{idx} wildcard is only supported as a suffix")
    if target not in TARGETS:
        raise ValueError(f"unknown target '{target}' in route #{idx}")
    return {"path": path, "target": target}


def load_routes(routing_table: Path) -> list[Route]:
    data = json.loads(routing_table.read_text())
    raw_routes = data.get("routes", [])
    if not isinstance(raw_routes, list):
        raise ValueError("routing table field 'routes' must be a list")

    routes = [_validate_route(route, idx) for idx, route in enumerate(raw_routes)]
    return sorted(routes, key=_route_specificity, reverse=True)


def generate_caddyfile(routes: list[Route]) -> str:
    lines: list[str] = [
        "# Generated by local-dev/caddy/build_caddyfile.py.",
        "# Edit local-dev/routing-table.json and run `make reload-routing`.",
        "",
        ":8080 {",
        "\tlog {",
        "\t\toutput stdout",
        "\t\tformat console",
        "\t}",
        "",
        "\theader {",
        '\t\tAccess-Control-Allow-Origin "http://localhost:5173"',
        '\t\tAccess-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS"',
        '\t\tAccess-Control-Allow-Headers "Authorization, Content-Type, X-Xray-Session"',
        '\t\tAccess-Control-Allow-Credentials "true"',
        "\t}",
        "",
        "\t@preflight method OPTIONS",
        "\trespond @preflight 204",
        "",
    ]
    for idx, route in enumerate(routes):
        path = route["path"]
        target_name = route["target"]
        upstream = TARGETS[target_name]
        matcher = f"@r{idx}"
        lines.extend(
            [
                f"\t{matcher} path {path}",
                f"\treverse_proxy {matcher} {upstream} {{",
                "\t\tflush_interval -1",
                "\t\theader_up X-Hub-Router {{placeholder}}".replace(
                    "{{placeholder}}", target_name
                ),
                "\t}",
                "",
            ]
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--routing-table", type=Path, default=ROUTING_TABLE)
    parser.add_argument("--output", type=Path, default=CADDYFILE)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate that the output file already matches the routing table",
    )
    args = parser.parse_args(argv)

    try:
        routes = load_routes(args.routing_table)
        rendered = generate_caddyfile(routes)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"routing table error: {exc}", file=sys.stderr)
        return 1

    if args.check:
        try:
            existing = args.output.read_text()
        except OSError as exc:
            print(f"cannot read {args.output}: {exc}", file=sys.stderr)
            return 1
        if existing != rendered:
            print(f"{args.output} is stale; run `make reload-routing`", file=sys.stderr)
            return 1
        print(f"{args.output} is up to date")
        return 0

    args.output.write_text(rendered)
    print(f"wrote {args.output} with {len(routes)} route(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
