# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomSidebarSections",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("agent_id", models.TextField()),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("section_schema", models.TextField(blank=True, null=True)),
                ("data_sources", models.JSONField(blank=True, null=True)),
                ("created_by", models.TextField()),
                ("proposal_id", models.TextField(blank=True, null=True)),
                ("is_shared", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "custom_sidebar_sections",
            },
        ),
        migrations.CreateModel(
            name="RoleTemplates",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("role_name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("agent_permissions", models.TextField()),
                ("sidebar_default", models.TextField(blank=True, null=True)),
                ("brief_agents", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "role_templates",
            },
        ),
        migrations.CreateModel(
            name="SharingConfig",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("target_hub_url", models.TextField()),
                ("target_hub_name", models.TextField(blank=True, null=True)),
                ("fields_shared", models.TextField(blank=True, null=True)),
                ("secret", models.TextField(blank=True, null=True)),
                ("granted_by", models.TextField(blank=True, null=True)),
                ("active", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sharing_config",
            },
        ),
        migrations.CreateModel(
            name="SidebarSectionShares",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("section_id", models.TextField()),
                ("shared_by", models.TextField()),
                ("shared_with", models.TextField()),
                ("status", models.TextField(blank=True, null=True)),
                ("shared_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sidebar_section_shares",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("user_email", models.TextField(unique=True)),
                ("default_view", models.TextField(blank=True, null=True)),
                ("sidebar_order_json", models.JSONField(blank=True, null=True)),
                ("brief_emphasis_json", models.JSONField(blank=True, null=True)),
                ("notification_filters_json", models.JSONField(blank=True, null=True)),
                ("dashboard_layout_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("agent_domains", models.JSONField(blank=True, null=True)),
                ("pinned_items", models.JSONField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("vault_pin", models.TextField(blank=True, null=True)),
                ("onboarding_completed", models.IntegerField()),
                ("display_settings", models.JSONField(blank=True, null=True)),
                ("agent_sort_pref", models.TextField(blank=True, null=True)),
                ("pinned_agents", models.JSONField(blank=True, null=True)),
                ("hide_inactive_agents", models.IntegerField(blank=True, null=True)),
                ("team_tour_completed", models.IntegerField(blank=True, null=True)),
                ("team_tour_data", models.JSONField(blank=True, null=True)),
                ("last_brief_generated", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="FeatureAnnouncementViews",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("announcement_id", models.TextField()),
                ("user_email", models.TextField()),
                ("shown_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "feature_announcement_views",
                "unique_together": {("announcement_id", "user_email")},
            },
        ),
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                ("email", models.TextField(primary_key=True, serialize=False)),
                ("type", models.TextField()),
                ("in_app", models.IntegerField()),
                ("push_email", models.IntegerField()),
                ("sound", models.IntegerField()),
            ],
            options={
                "db_table": "notification_preferences",
                "unique_together": {("email", "type")},
            },
        ),
        migrations.CreateModel(
            name="UserAgentPermissions",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("user_email", models.TextField()),
                ("agent_id", models.TextField()),
                ("can_view", models.IntegerField(blank=True, null=True)),
                ("can_chat", models.IntegerField(blank=True, null=True)),
                ("can_approve", models.IntegerField(blank=True, null=True)),
                ("can_see_financials", models.IntegerField(blank=True, null=True)),
                ("can_configure", models.IntegerField(blank=True, null=True)),
                ("can_execute", models.IntegerField(blank=True, null=True)),
                ("set_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("tone", models.TextField(blank=True, null=True)),
                ("language", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_agent_permissions",
                "unique_together": {("user_email", "agent_id")},
            },
        ),
        migrations.CreateModel(
            name="UserFeatureUsage",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("user_email", models.TextField()),
                ("feature_key", models.TextField()),
                ("first_used_at", models.DateTimeField(blank=True, null=True)),
                ("use_count", models.IntegerField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_feature_usage",
                "unique_together": {("user_email", "feature_key")},
            },
        ),
    ]
