# Generated by Django 5.1.15 on 2026-04-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hub_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentArtifacts",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("agent_id", models.TextField()),
                ("user_email", models.TextField()),
                ("title", models.TextField()),
                ("artifact_type", models.TextField()),
                ("content_html", models.TextField(blank=True, null=True)),
                ("content_markdown", models.TextField(blank=True, null=True)),
                ("template", models.TextField(blank=True, null=True)),
                ("file_url", models.TextField(blank=True, null=True)),
                ("run_id", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("brief_type", models.TextField(blank=True, null=True)),
                ("assigned_to", models.TextField(blank=True, null=True)),
                ("assigned_by", models.TextField(blank=True, null=True)),
                ("presenting_agent_id", models.TextField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("shared_thread_id", models.TextField(blank=True, null=True)),
                ("published_url", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("publish_target", models.TextField(blank=True, null=True)),
                ("publish_slug", models.TextField(blank=True, null=True)),
                ("publish_status", models.TextField(blank=True, null=True)),
                ("media_type", models.TextField(blank=True, null=True)),
                ("source_file", models.TextField(blank=True, null=True)),
                ("contact_id", models.TextField(blank=True, null=True)),
                ("company_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "agent_artifacts",
            },
        ),
        migrations.CreateModel(
            name="AskActions",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("conversation_id", models.TextField(blank=True, null=True)),
                ("message_id", models.TextField(blank=True, null=True)),
                ("action_type", models.TextField()),
                ("action_params_json", models.JSONField(blank=True, null=True)),
                ("status", models.TextField()),
                ("confirmed_by", models.TextField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("result_json", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "ask_actions",
            },
        ),
        migrations.CreateModel(
            name="AskConversations",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("user_email", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("agents_json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "ask_conversations",
            },
        ),
        migrations.CreateModel(
            name="AskResponses",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("ask_id", models.TextField()),
                ("investor_profile_id", models.TextField()),
                ("investor_name", models.TextField()),
                ("body", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "ask_responses",
            },
        ),
        migrations.CreateModel(
            name="Asks",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("type", models.TextField()),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("target", models.TextField(blank=True, null=True)),
                ("target_investor_ids", models.TextField(blank=True, null=True)),
                ("status", models.TextField()),
                ("created_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "asks",
            },
        ),
        migrations.CreateModel(
            name="BriefActions",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("source_type", models.TextField()),
                ("source_id", models.TextField()),
                ("action_type", models.TextField()),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("assigned_to", models.TextField(blank=True, null=True)),
                ("due_date", models.TextField(blank=True, null=True)),
                ("calendar_event_id", models.TextField(blank=True, null=True)),
                ("task_id", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "brief_actions",
            },
        ),
        migrations.CreateModel(
            name="BriefCards",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("user_email", models.TextField()),
                ("agent_id", models.TextField()),
                ("title", models.TextField(blank=True, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("zone", models.TextField(blank=True, null=True)),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("action_label", models.TextField(blank=True, null=True)),
                ("action_type", models.TextField(blank=True, null=True)),
                ("action_payload", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "brief_cards",
            },
        ),
        migrations.CreateModel(
            name="BriefPreferences",
            fields=[
                ("email", models.TextField(primary_key=True, serialize=False)),
                ("daily_enabled", models.IntegerField()),
                ("weekly_enabled", models.IntegerField()),
                ("delivery_time", models.TextField()),
                ("timezone", models.TextField()),
                ("format", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "brief_preferences",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplates",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("subject_template", models.TextField()),
                ("body_template", models.TextField()),
                ("category", models.TextField()),
                ("entity_id", models.TextField(blank=True, null=True)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("variables_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "email_templates",
            },
        ),
        migrations.CreateModel(
            name="AskMessages",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("role", models.TextField()),
                ("content", models.TextField()),
                ("sources_json", models.JSONField(blank=True, null=True)),
                ("agent", models.TextField(blank=True, null=True)),
                ("model", models.TextField(blank=True, null=True)),
                ("confidence", models.TextField(blank=True, null=True)),
                ("follow_ups_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="brief.askconversations"
                    ),
                ),
            ],
            options={
                "db_table": "ask_messages",
            },
        ),
        migrations.CreateModel(
            name="BriefCache",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("user_email", models.TextField()),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("sections_json", models.JSONField()),
                ("strip_json", models.JSONField(blank=True, null=True)),
                ("generated_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "brief_cache",
                "unique_together": {("user_email", "tenant_id")},
            },
        ),
        migrations.CreateModel(
            name="BriefDeliveries",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("type", models.TextField()),
                ("status", models.TextField()),
                ("error", models.TextField(blank=True, null=True)),
                ("resend_id", models.TextField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField()),
                (
                    "user_email",
                    models.ForeignKey(
                        db_column="user_email",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hub_auth.people",
                        to_field="email",
                    ),
                ),
            ],
            options={
                "db_table": "brief_deliveries",
            },
        ),
        migrations.CreateModel(
            name="BriefPins",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("item_id", models.TextField()),
                ("item_type", models.TextField()),
                ("user_email", models.TextField()),
                ("title", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "brief_pins",
                "unique_together": {("item_id", "user_email")},
            },
        ),
    ]
