# Convenience wrapper for local-dev commands.

.PHONY: reload-routing verify-TKT-011 verify-TKT-012 verify-TKT-013 verify-TKT-014 verify-TKT-015 verify-TKT-017 verify-TKT-018 verify-TKT-019 verify-TKT-020 verify-TKT-021 verify-TKT-022 verify-TKT-023 verify-ticket

reload-routing:
	$(MAKE) -C .. reload-routing

verify-TKT-011:
	$(MAKE) -C .. verify-TKT-011

verify-TKT-012:
	$(MAKE) -C .. verify-TKT-012

verify-TKT-013:
	$(MAKE) -C .. verify-TKT-013

verify-TKT-014:
	$(MAKE) -C .. verify-TKT-014

verify-TKT-015:
	$(MAKE) -C .. verify-TKT-015

verify-TKT-017:
	$(MAKE) -C .. verify-TKT-017

verify-TKT-018:
	$(MAKE) -C .. verify-TKT-018

verify-TKT-019:
	$(MAKE) -C .. verify-TKT-019

verify-TKT-020:
	$(MAKE) -C .. verify-TKT-020

verify-TKT-021:
	$(MAKE) -C .. verify-TKT-021

verify-TKT-022:
	$(MAKE) -C .. verify-TKT-022

verify-TKT-023:
	$(MAKE) -C .. verify-TKT-023

verify-ticket:
	$(MAKE) -C .. verify-ticket TKT=$(TKT)
