# Convenience wrapper for local-dev commands.

.PHONY: reload-routing verify-TKT-011 verify-TKT-012 verify-TKT-013

reload-routing:
	$(MAKE) -C .. reload-routing

verify-TKT-011:
	$(MAKE) -C .. verify-TKT-011

verify-TKT-012:
	$(MAKE) -C .. verify-TKT-012

verify-TKT-013:
	$(MAKE) -C .. verify-TKT-013
