# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeployVerifications",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("git_sha", models.TextField(blank=True, null=True)),
                ("session_id", models.TextField(blank=True, null=True)),
                ("triggered_by", models.TextField(blank=True, null=True)),
                ("total_checks", models.IntegerField(blank=True, null=True)),
                ("passed", models.IntegerField(blank=True, null=True)),
                ("failed", models.IntegerField(blank=True, null=True)),
                ("overall", models.TextField(blank=True, null=True)),
                ("results_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "deploy_verifications",
            },
        ),
        migrations.CreateModel(
            name="ProviderHealth",
            fields=[
                ("provider", models.TextField(primary_key=True, serialize=False)),
                ("status", models.TextField(blank=True, null=True)),
                ("last_check", models.TextField(blank=True, null=True)),
                ("last_success", models.TextField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("error_rate_1h", models.FloatField(blank=True, null=True)),
                ("latency_p95_ms", models.IntegerField(blank=True, null=True)),
                ("consecutive_failures", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "provider_health",
            },
        ),
        migrations.CreateModel(
            name="ReleaseNotes",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("session_id", models.TextField(blank=True, null=True)),
                ("title", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("features", models.JSONField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("commit_hash", models.TextField(blank=True, null=True)),
                ("commit_date", models.TextField(blank=True, null=True)),
                ("files_changed", models.IntegerField(blank=True, null=True)),
                ("chain", models.TextField(blank=True, null=True)),
                ("author", models.TextField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "release_notes",
            },
        ),
        migrations.CreateModel(
            name="RetryQueue",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("agent_id", models.TextField()),
                ("user_email", models.TextField()),
                ("prompt", models.TextField()),
                ("conversation_id", models.TextField(blank=True, null=True)),
                ("original_error", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "retry_queue",
            },
        ),
        migrations.CreateModel(
            name="StatusChecks",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("service", models.TextField()),
                ("endpoint", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("response_ms", models.IntegerField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "status_checks",
            },
        ),
        migrations.CreateModel(
            name="StatusIncidents",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("service", models.TextField()),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("severity", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "status_incidents",
            },
        ),
    ]
