# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkConnections",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("owner_email", models.TextField()),
                ("owner_name", models.TextField(blank=True, null=True)),
                ("connection_name", models.TextField()),
                ("connection_email", models.TextField(blank=True, null=True)),
                ("connection_linkedin", models.TextField(blank=True, null=True)),
                ("connection_company", models.TextField(blank=True, null=True)),
                ("connection_title", models.TextField(blank=True, null=True)),
                ("relationship", models.TextField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "network_connections",
            },
        ),
    ]
