# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("email", models.TextField(unique=True)),
                ("display_name", models.TextField()),
                ("role", models.TextField()),
                ("tier", models.TextField()),
                ("title", models.TextField(blank=True, null=True)),
                ("division", models.TextField(blank=True, null=True)),
                ("entity_access", models.JSONField()),
                ("scopes", models.JSONField()),
                ("agents", models.JSONField()),
                ("default_agent", models.TextField(blank=True, null=True)),
                ("status", models.TextField()),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("monitoring_tier", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("photo_url", models.TextField(blank=True, null=True)),
                ("department", models.TextField(blank=True, null=True)),
                ("is_workspace_admin", models.IntegerField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "people",
            },
        ),
        migrations.CreateModel(
            name="UserIdentityLinks",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("user_id", models.TextField()),
                ("email", models.TextField(unique=True)),
                ("email_type", models.TextField(blank=True, null=True)),
                ("is_primary", models.IntegerField(blank=True, null=True)),
                ("verified", models.IntegerField(blank=True, null=True)),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                ("linked_by", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_identity_links",
            },
        ),
        migrations.CreateModel(
            name="UserTenants",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("user_email", models.TextField()),
                ("tenant_id", models.TextField()),
                ("role", models.TextField(blank=True, null=True)),
                ("is_owner", models.IntegerField(blank=True, null=True)),
                ("is_admin", models.IntegerField(blank=True, null=True)),
                ("joined_at", models.DateTimeField()),
                ("access_tier", models.IntegerField(blank=True, null=True)),
                ("ui_mode", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_tenants",
                "unique_together": {("user_email", "tenant_id")},
            },
        ),
    ]
