# Generated by Django 5.2.13 on 2026-04-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("display_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("normal", "normal"),
                            ("staff", "staff"),
                            ("superadmin", "superadmin"),
                        ],
                        default="normal",
                        help_text="normal = default user; staff = Django-admin viewer; superadmin = impersonation + destructive admin.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "People",
                "db_table": "people",
            },
        ),
    ]
