# Generated by Django 5.2.13 on 2026-04-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="role",
            field=models.CharField(
                choices=[("normal", "normal"), ("staff", "staff"), ("superadmin", "superadmin")],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("token", models.CharField(max_length=200, primary_key=True, serialize=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="hub_auth.people",
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
            },
        ),
    ]
