# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OnboardingSavings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("tool_name", models.TextField()),
                ("category", models.TextField()),
                ("reported_cost_cents", models.IntegerField()),
                ("hub_replacement", models.TextField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "onboarding_savings",
            },
        ),
        migrations.CreateModel(
            name="OnboardingSessions",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("company_id", models.TextField(blank=True, null=True)),
                ("step", models.IntegerField(blank=True, null=True)),
                ("data", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "onboarding_sessions",
            },
        ),
    ]
