# Generated by Django 5.1.15 on 2026-04-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConnectorConfigs",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("provider", models.TextField(unique=True)),
                ("status", models.TextField()),
                ("connected_by", models.TextField(blank=True, null=True)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync", models.TextField(blank=True, null=True)),
                ("sync_frequency", models.IntegerField(blank=True, null=True)),
                ("settings", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("sync_count", models.IntegerField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "connector_configs",
            },
        ),
        migrations.CreateModel(
            name="ConnectorRegistry",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("provider", models.TextField()),
                ("connector_type", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("data_scope", models.TextField(blank=True, null=True)),
                ("health_score", models.FloatField(blank=True, null=True)),
                ("last_sync", models.TextField(blank=True, null=True)),
                ("lifecycle_stage", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "connector_registry",
            },
        ),
        migrations.CreateModel(
            name="Connectors",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("user_email", models.TextField()),
                ("provider", models.TextField()),
                ("status", models.TextField()),
                ("last_sync", models.TextField(blank=True, null=True)),
                ("config_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "connectors",
            },
        ),
        migrations.CreateModel(
            name="ConnectorSyncLog",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("provider", models.TextField()),
                ("status", models.TextField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "connector_sync_log",
            },
        ),
        migrations.CreateModel(
            name="HubExternalData",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("source_hub_url", models.TextField()),
                ("source_hub_name", models.TextField(blank=True, null=True)),
                ("field", models.TextField()),
                ("value", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "hub_external_data",
            },
        ),
        migrations.CreateModel(
            name="PrivacyBrokers",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("domain", models.TextField()),
                ("opt_out_url", models.TextField(blank=True, null=True)),
                ("scan_enabled", models.IntegerField(blank=True, null=True)),
                ("removal_enabled", models.IntegerField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("difficulty", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "privacy_brokers",
            },
        ),
        migrations.CreateModel(
            name="PrivacyRemovals",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("subscriber_id", models.TextField()),
                ("scan_id", models.TextField(blank=True, null=True)),
                ("broker_name", models.TextField()),
                ("broker_url", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("method", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "privacy_removals",
            },
        ),
        migrations.CreateModel(
            name="PrivacyScans",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("subscriber_id", models.TextField()),
                ("status", models.TextField(blank=True, null=True)),
                ("scan_type", models.TextField(blank=True, null=True)),
                ("brokers_checked", models.IntegerField(blank=True, null=True)),
                ("brokers_found", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("results_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "privacy_scans",
            },
        ),
        migrations.CreateModel(
            name="PrivacySubscribers",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("email", models.TextField()),
                ("first_name", models.TextField(blank=True, null=True)),
                ("last_name", models.TextField(blank=True, null=True)),
                ("plan", models.TextField(blank=True, null=True)),
                ("stripe_customer_id", models.TextField(blank=True, null=True)),
                ("stripe_subscription_id", models.TextField(blank=True, null=True)),
                ("pii_json", models.JSONField(blank=True, null=True)),
                ("scan_status", models.TextField(blank=True, null=True)),
                ("last_scan_at", models.DateTimeField(blank=True, null=True)),
                ("broker_count", models.IntegerField(blank=True, null=True)),
                ("removed_count", models.IntegerField(blank=True, null=True)),
                ("active", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "privacy_subscribers",
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.TextField()),
                ("records_synced", models.IntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="connectors.connectorconfigs",
                    ),
                ),
            ],
            options={
                "db_table": "sync_log",
            },
        ),
    ]
