# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarEvents",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("connector_id", models.TextField()),
                ("event_id", models.TextField(unique=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("start_time", models.TextField(blank=True, null=True)),
                ("end_time", models.TextField(blank=True, null=True)),
                ("attendees", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("entity_id", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("listener_processed", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "calendar_events",
            },
        ),
        migrations.CreateModel(
            name="FilingDeadlines",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("entity", models.TextField()),
                ("filing_type", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.TextField()),
                ("status", models.TextField(blank=True, null=True)),
                ("owner", models.TextField(blank=True, null=True)),
                ("reminder_sent_30d", models.IntegerField(blank=True, null=True)),
                ("reminder_sent_14d", models.IntegerField(blank=True, null=True)),
                ("reminder_sent_7d", models.IntegerField(blank=True, null=True)),
                ("reminder_sent_1d", models.IntegerField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "filing_deadlines",
            },
        ),
    ]
