# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReconciliationLog",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("period", models.TextField()),
                ("bank_balance", models.FloatField(blank=True, null=True)),
                ("qb_balance", models.FloatField(blank=True, null=True)),
                ("hub_balance", models.FloatField(blank=True, null=True)),
                ("discrepancy", models.FloatField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "reconciliation_log",
            },
        ),
        migrations.CreateModel(
            name="ReconciliationTasks",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("period", models.TextField()),
                ("task_type", models.TextField()),
                ("description", models.TextField()),
                ("bank_txn_id", models.TextField(blank=True, null=True)),
                ("qb_txn_id", models.TextField(blank=True, null=True)),
                ("hub_txn_id", models.TextField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("suggested_action", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("resolved_by", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("assigned_to", models.TextField(blank=True, null=True)),
                ("escalated_by", models.TextField(blank=True, null=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "reconciliation_tasks",
            },
        ),
    ]
