# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallTemplates",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("call_type", models.TextField(unique=True)),
                ("pre_call_prompt", models.TextField()),
                ("coaching_prompt", models.TextField()),
                ("post_call_prompt", models.TextField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "call_templates",
            },
        ),
        migrations.CreateModel(
            name="CallTranscripts",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("calendar_event_id", models.TextField(blank=True, null=True)),
                ("call_type", models.TextField(blank=True, null=True)),
                ("participants", models.JSONField(blank=True, null=True)),
                ("transcript", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("action_items", models.JSONField(blank=True, null=True)),
                ("follow_ups", models.JSONField(blank=True, null=True)),
                ("sentiment", models.TextField(blank=True, null=True)),
                ("coaching_notes", models.JSONField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("processed", models.IntegerField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "call_transcripts",
            },
        ),
        migrations.CreateModel(
            name="VoiceIntakes",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("user_email", models.TextField()),
                ("transcript", models.TextField()),
                ("intent", models.TextField()),
                ("routed_to", models.JSONField(blank=True, null=True)),
                ("target_person", models.TextField(blank=True, null=True)),
                ("target_entity", models.TextField(blank=True, null=True)),
                ("confirmation", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("result_id", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "voice_intakes",
            },
        ),
    ]
