# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionAudit",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("card_id", models.TextField(blank=True, null=True)),
                ("agent_id", models.TextField(blank=True, null=True)),
                ("action_type", models.TextField(blank=True, null=True)),
                ("action_label", models.TextField(blank=True, null=True)),
                ("user_email", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("result", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "action_audit",
            },
        ),
        migrations.CreateModel(
            name="AgentSuspensions",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("agent_id", models.TextField()),
                ("reason", models.TextField()),
                ("violation_id", models.TextField(blank=True, null=True)),
                ("suspended_by", models.TextField()),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("reinstated_by", models.TextField(blank=True, null=True)),
                ("reinstated_at", models.DateTimeField(blank=True, null=True)),
                ("reinstate_notes", models.TextField(blank=True, null=True)),
                ("probation_until", models.DateTimeField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "agent_suspensions",
            },
        ),
        migrations.CreateModel(
            name="AgentToolAudit",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("agent_id", models.TextField()),
                ("user_email", models.TextField(blank=True, null=True)),
                ("tool_type", models.TextField()),
                ("tool_name", models.TextField(blank=True, null=True)),
                ("input_summary", models.TextField(blank=True, null=True)),
                ("result_summary", models.TextField(blank=True, null=True)),
                ("autonomy_level", models.IntegerField(blank=True, null=True)),
                ("approved_by", models.TextField(blank=True, null=True)),
                ("blocked_by", models.TextField(blank=True, null=True)),
                ("cost_usd", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "agent_tool_audit",
            },
        ),
        migrations.CreateModel(
            name="AuditFindings",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("category", models.TextField()),
                ("severity", models.TextField()),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("file_path", models.TextField(blank=True, null=True)),
                ("line_number", models.IntegerField(blank=True, null=True)),
                ("status", models.TextField()),
                ("found_by", models.TextField(blank=True, null=True)),
                ("fixed_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField()),
            ],
            options={
                "db_table": "audit_findings",
            },
        ),
        migrations.CreateModel(
            name="AuditRuns",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("run_type", models.TextField()),
                ("findings_count", models.IntegerField(blank=True, null=True)),
                ("critical_count", models.IntegerField(blank=True, null=True)),
                ("warning_count", models.IntegerField(blank=True, null=True)),
                ("info_count", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("triggered_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("tenant_id", models.TextField()),
            ],
            options={
                "db_table": "audit_runs",
            },
        ),
        migrations.CreateModel(
            name="BugReports",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("user_email", models.TextField(blank=True, null=True)),
                ("page", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "bug_reports",
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("type", models.TextField()),
                ("entity_id", models.TextField(blank=True, null=True)),
                ("actor", models.TextField()),
                ("target_type", models.TextField(blank=True, null=True)),
                ("target_id", models.TextField(blank=True, null=True)),
                ("detail", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "events",
            },
        ),
        migrations.CreateModel(
            name="PlatformPolicies",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("policy_type", models.TextField()),
                ("version", models.TextField()),
                ("title", models.TextField()),
                ("content", models.TextField()),
                ("effective_date", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "platform_policies",
            },
        ),
        migrations.CreateModel(
            name="PlatformViolations",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("entity_type", models.TextField()),
                ("entity_id", models.TextField()),
                ("violation_type", models.TextField()),
                ("severity", models.TextField()),
                ("description", models.TextField()),
                ("evidence", models.TextField(blank=True, null=True)),
                ("policy_reference", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True, null=True)),
                ("resolved_by", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "platform_violations",
            },
        ),
        migrations.CreateModel(
            name="SecurityControls",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("category", models.TextField()),
                ("control_name", models.TextField()),
                ("status", models.TextField(blank=True, null=True)),
                ("evidence", models.TextField(blank=True, null=True)),
                ("last_verified", models.TextField(blank=True, null=True)),
                ("responsible", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "security_controls",
            },
        ),
    ]
