# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HubKnowledge",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("filename", models.TextField()),
                ("content", models.TextField()),
                ("category", models.TextField()),
                ("updated_at", models.DateTimeField()),
                ("section_slug", models.TextField(blank=True, null=True)),
                ("assigned_to", models.TextField(blank=True, null=True)),
                ("entry_type", models.TextField(blank=True, null=True)),
                ("searchable_keywords", models.TextField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("access_tier", models.IntegerField(blank=True, null=True)),
                ("knowledge_domain", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "hub_knowledge",
            },
        ),
    ]
