# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StreamEntries",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("hub_id", models.TextField()),
                ("source_type", models.TextField()),
                ("source_id", models.TextField(blank=True, null=True)),
                ("agent_id", models.TextField(blank=True, null=True)),
                ("user_email", models.TextField(blank=True, null=True)),
                ("event_type", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("payload_json", models.JSONField(blank=True, null=True)),
                ("visibility", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "stream_entries",
            },
        ),
    ]
