# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CapTableEntries",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("investor_profile_id", models.TextField(blank=True, null=True)),
                ("name", models.TextField()),
                ("type", models.TextField()),
                ("class_field", models.TextField(db_column="class")),
                ("units", models.IntegerField()),
                ("invested_amount", models.IntegerField()),
                ("post_pref_pct", models.FloatField()),
                ("post_eip_pct", models.FloatField()),
                ("voting_pct", models.FloatField()),
                ("vesting", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("portal_visible", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "cap_table_entries",
            },
        ),
        migrations.CreateModel(
            name="FundDocuments",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("category", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("doc_url", models.TextField(blank=True, null=True)),
                ("file_name", models.TextField(blank=True, null=True)),
                ("visibility", models.TextField()),
                ("published_date", models.TextField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "fund_documents",
            },
        ),
        migrations.CreateModel(
            name="FundMetrics",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("period", models.TextField()),
                ("fund_size", models.FloatField()),
                ("committed", models.FloatField()),
                ("deployed", models.FloatField()),
                ("distributions", models.FloatField()),
                ("irr", models.FloatField(blank=True, null=True)),
                ("tvpi", models.FloatField(blank=True, null=True)),
                ("dpi", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "fund_metrics",
            },
        ),
        migrations.CreateModel(
            name="FundraiseCampaignProspects",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("campaign_id", models.TextField()),
                ("investor_id", models.TextField()),
                ("sequence_id", models.TextField(blank=True, null=True)),
                ("page_token", models.TextField(blank=True, null=True)),
                ("page_artifact_id", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "fundraise_campaign_prospects",
            },
        ),
        migrations.CreateModel(
            name="FundraiseCampaigns",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("name", models.TextField()),
                ("raise_id", models.TextField(blank=True, null=True)),
                ("icp_description", models.TextField(blank=True, null=True)),
                ("instrument", models.TextField(blank=True, null=True)),
                ("valuation_cap", models.FloatField(blank=True, null=True)),
                ("min_check", models.FloatField(blank=True, null=True)),
                ("cadence_template_id", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("stats_json", models.JSONField(blank=True, null=True)),
                ("playbook_json", models.JSONField(blank=True, null=True)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "fundraise_campaigns",
            },
        ),
        migrations.CreateModel(
            name="FundraiseTracking",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("entity_id", models.TextField()),
                ("raise_name", models.TextField()),
                ("target_amount", models.FloatField()),
                ("committed_amount", models.FloatField()),
                ("owner", models.TextField()),
                ("status", models.TextField()),
                ("stage", models.TextField()),
                ("vehicle", models.TextField(blank=True, null=True)),
                ("deadline", models.TextField(blank=True, null=True)),
                ("next_action", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "fundraise_tracking",
            },
        ),
        migrations.CreateModel(
            name="IcMeetings",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("date", models.TextField()),
                ("attendees", models.TextField(blank=True, null=True)),
                ("agenda", models.TextField(blank=True, null=True)),
                ("minutes", models.TextField(blank=True, null=True)),
                ("deals_reviewed", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ic_meetings",
            },
        ),
        migrations.CreateModel(
            name="IcVotes",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("deal_id", models.TextField()),
                ("voter_email", models.TextField()),
                ("vote", models.TextField()),
                ("rationale", models.TextField(blank=True, null=True)),
                ("conditions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ic_votes",
            },
        ),
        migrations.CreateModel(
            name="InvestorEngagementLog",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("investor_id", models.TextField()),
                ("viewer_email", models.TextField()),
                ("page", models.TextField(blank=True, null=True)),
                ("event", models.TextField()),
                ("notified_to", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "investor_engagement_log",
            },
        ),
        migrations.CreateModel(
            name="InvestorProfiles",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("entity_name", models.TextField(blank=True, null=True)),
                ("amount_committed", models.IntegerField(blank=True, null=True)),
                ("amount_funded", models.IntegerField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("tranche", models.IntegerField(blank=True, null=True)),
                ("docs_signed", models.IntegerField(blank=True, null=True)),
                ("date_funded", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("share_token", models.TextField(blank=True, null=True)),
                ("last_view_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "investor_profiles",
            },
        ),
        migrations.CreateModel(
            name="InvestorTransactions",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("investor_id", models.TextField()),
                ("type", models.TextField()),
                ("amount", models.FloatField()),
                ("date", models.TextField()),
                ("status", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "investor_transactions",
            },
        ),
        migrations.CreateModel(
            name="InvestorUpdates",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("content", models.TextField()),
                ("date", models.TextField()),
                ("visibility", models.TextField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "investor_updates",
            },
        ),
        migrations.CreateModel(
            name="InvestorUsers",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("email", models.TextField(unique=True)),
                ("investor_id", models.TextField()),
                ("name", models.TextField()),
                ("status", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "investor_users",
            },
        ),
        migrations.CreateModel(
            name="ProspectDecisions",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField(blank=True, null=True)),
                ("investor_id", models.TextField()),
                ("campaign_id", models.TextField(blank=True, null=True)),
                ("decision", models.TextField()),
                ("reason", models.TextField(blank=True, null=True)),
                ("decided_by", models.TextField()),
                ("attributes_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "prospect_decisions",
            },
        ),
    ]
