# Generated by Django 5.1.15 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureAnnouncements",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("feature_key", models.TextField()),
                ("title", models.TextField()),
                ("body", models.TextField()),
                ("relevant_roles", models.TextField(blank=True, null=True)),
                ("action_label", models.TextField(blank=True, null=True)),
                ("action_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "feature_announcements",
            },
        ),
        migrations.CreateModel(
            name="HubNotifications",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("user_email", models.TextField()),
                ("type", models.TextField()),
                ("title", models.TextField()),
                ("body", models.TextField(blank=True, null=True)),
                ("link", models.TextField(blank=True, null=True)),
                ("source_agent_id", models.TextField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "hub_notifications",
            },
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("user_email", models.TextField()),
                ("type", models.TextField()),
                ("title", models.TextField()),
                ("body", models.TextField(blank=True, null=True)),
                ("action_url", models.TextField(blank=True, null=True)),
                ("is_read", models.IntegerField()),
                ("entity_id", models.TextField(blank=True, null=True)),
                ("source", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("tenant_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "notifications",
            },
        ),
        migrations.CreateModel(
            name="PageTips",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("user_email", models.TextField()),
                ("page_id", models.TextField()),
                ("tip_text", models.TextField()),
                ("capabilities_json", models.JSONField(blank=True, null=True)),
                ("dismissed", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "page_tips",
                "unique_together": {("user_email", "page_id")},
            },
        ),
        migrations.CreateModel(
            name="TourGuideProgress",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tenant_id", models.TextField()),
                ("user_email", models.TextField()),
                ("step_type", models.TextField()),
                ("step_id", models.TextField()),
                ("status", models.TextField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tour_guide_progress",
                "unique_together": {("user_email", "step_id")},
            },
        ),
    ]
